import { jsx as _jsx } from "react/jsx-runtime";
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { ProjectContextProvider } from './store/ProjectContext';
import { BlogsContextProvider } from './store/BolgsContext';
// import { LightDarkContextProvider } from './store/LightDarkContext';
import { AuthProvider } from '@/store/AuthContext';
import App from './App';
import './index.css';
createRoot(document.getElementById('root')).render(_jsx(AuthProvider, { children: _jsx(StrictMode, { children: _jsx(ProjectContextProvider, { children: _jsx(BlogsContextProvider, { children: _jsx(App, {}) }) }) }) }));
